spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.113:3306/schema_block?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: Fenix-block
  redis:
    host: 192.168.0.113
    port: 6379
  rabbitmq:
    host: 192.168.0.113
    port: 5672
    virtual-host: /

#mybatis-plus:
#  config-location: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0

server:
  port: 8083

