spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.107:3306/schema_user?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    type: com.alibaba.druid.pool.DruidDataSource

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: Fenix-user

  redis:
    host: 192.168.0.106
    port: 6379
server:
  port: 8082


